environment: 
 NugetApiKey:
  secure: 9d4b47bd-2111-4ed2-8c66-9cf4d0712a18

build: false

#Kick off the CI/CD pipeline
before_test: 
 - echo "started"
 - ps: install-module invokebuild
 - echo "installed"
 - ps: import-module invokebuild
 - echo "imported"
test_script:
  - ps: . .\main.build.ps1
